import "dotenv/config"
import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const db = new PrismaClient()

async function main() {
  const pw = await bcrypt.hash("Test1234!", 12)

  // â”€â”€ Users â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.user.upsert({ where: { email: "client@volcanoarts.rw" }, update: {}, create: { email: "client@volcanoarts.rw", firstName: "Test", lastName: "Client", password: pw, role: "REGISTERED_CLIENT" } })
  await db.user.upsert({ where: { email: "talent@volcanoarts.rw" }, update: {}, create: { email: "talent@volcanoarts.rw", firstName: "Amina", lastName: "Uwase", password: pw, role: "TALENT_APPLICANT" } })
  await db.user.upsert({ where: { email: "operator@volcanoarts.rw" }, update: {}, create: { email: "operator@volcanoarts.rw", firstName: "Safari", lastName: "Tours", password: pw, role: "TOUR_OPERATOR" } })
  await db.user.upsert({ where: { email: "content@volcanoarts.rw" }, update: {}, create: { email: "content@volcanoarts.rw", firstName: "Content", lastName: "Manager", password: pw, role: "CONTENT_MANAGER" } })
  await db.user.upsert({ where: { email: "ops@volcanoarts.rw" }, update: {}, create: { email: "ops@volcanoarts.rw", firstName: "Ops", lastName: "Manager", password: pw, role: "OPS_MANAGER" } })
  await db.user.upsert({ where: { email: "admin@volcanoarts.rw" }, update: {}, create: { email: "admin@volcanoarts.rw", firstName: "Super", lastName: "Admin", password: pw, role: "SUPER_ADMIN" } })

  // â”€â”€ Categories â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const [paintings, sculpture, textiles, photography] = await Promise.all([
    db.category.upsert({ where: { slug: "paintings" }, update: {}, create: { name: "Paintings", slug: "paintings", description: "Original paintings from Rwandan artists" } }),
    db.category.upsert({ where: { slug: "sculpture" }, update: {}, create: { name: "Sculpture", slug: "sculpture", description: "Traditional and contemporary sculpture" } }),
    db.category.upsert({ where: { slug: "textiles" }, update: {}, create: { name: "Textiles", slug: "textiles", description: "Handwoven baskets and imigongo art" } }),
    db.category.upsert({ where: { slug: "photography" }, update: {}, create: { name: "Photography", slug: "photography", description: "Fine art photography of Rwanda" } }),
  ])

  // â”€â”€ Products â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const productData = [
    { name: "Volcanic Sunrise", slug: "volcanic-sunrise", artistName: "Jean-Pierre Habimana", price: "1200.00", compareAtPrice: "1500.00", categoryId: paintings.id, medium: "Oil on canvas", dimensions: "80 Ã— 60 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: true, status: "PUBLISHED" as const, description: "A breathtaking oil painting capturing the sunrise over the Virunga volcanoes." },
    { name: "Gorilla Guardian", slug: "gorilla-guardian", artistName: "Marie Mukamana", price: "950.00", categoryId: paintings.id, medium: "Acrylic on canvas", dimensions: "60 Ã— 90 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: true, status: "PUBLISHED" as const, description: "A powerful portrait of a mountain gorilla in its natural habitat." },
    { name: "Kigali Rhythm", slug: "kigali-rhythm", artistName: "Eric Nzeyimana", price: "780.00", categoryId: paintings.id, medium: "Mixed media", dimensions: "50 Ã— 70 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: false, status: "PUBLISHED" as const, description: "Abstract expressionism capturing the vibrant energy of Kigali city life." },
    { name: "Stone Elder", slug: "stone-elder", artistName: "Claudine Ingabire", price: "2400.00", categoryId: sculpture.id, medium: "Volcanic stone", dimensions: "40 Ã— 20 Ã— 20 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: true, status: "PUBLISHED" as const, description: "Hand-carved volcanic stone sculpture representing ancestral wisdom." },
    { name: "Dancing Figures", slug: "dancing-figures", artistName: "Patrick Nkurunziza", price: "1800.00", categoryId: sculpture.id, medium: "Bronze", dimensions: "60 Ã— 30 Ã— 15 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: false, status: "PUBLISHED" as const, description: "Bronze sculpture depicting traditional Intore dancers in full regalia." },
    { name: "Forest Spirit", slug: "forest-spirit", artistName: "Alice Uwimana", price: "3200.00", categoryId: sculpture.id, medium: "Wood and copper", dimensions: "90 Ã— 25 Ã— 25 cm", inventoryType: "UNIQUE" as const, stockQuantity: 1, featured: false, status: "PUBLISHED" as const, description: "Towering wooden sculpture with copper inlay representing the forest spirits." },
    { name: "Imigongo Set", slug: "imigongo-set", artistName: "Esperance Mukamurenzi", price: "320.00", compareAtPrice: "400.00", categoryId: textiles.id, medium: "Cow dung and natural pigments", dimensions: "30 Ã— 30 cm each", inventoryType: "BATCH" as const, stockQuantity: 8, featured: true, status: "PUBLISHED" as const, description: "Traditional Rwandan geometric art made from cow dung and earth pigments. Set of 3." },
    { name: "Agaseke Basket", slug: "agaseke-basket", artistName: "Vestine Nyiraneza", price: "180.00", categoryId: textiles.id, medium: "Sisal and sweetgrass", dimensions: "25 cm diameter", inventoryType: "BATCH" as const, stockQuantity: 12, featured: false, status: "PUBLISHED" as const, description: "Handwoven peace basket, a symbol of Rwandan cultural heritage and reconciliation." },
    { name: "Woven Dreams", slug: "woven-dreams", artistName: "Solange Mukandori", price: "240.00", categoryId: textiles.id, medium: "Natural fibers", dimensions: "40 Ã— 50 cm", inventoryType: "BATCH" as const, stockQuantity: 5, featured: false, status: "PUBLISHED" as const, description: "Intricate wall hanging woven from natural fibers with traditional patterns." },
    { name: "Mist and Mountain", slug: "mist-and-mountain", artistName: "David Mugabo", price: "850.00", compareAtPrice: "1100.00", categoryId: photography.id, medium: "Fine art print, archival paper", dimensions: "90 Ã— 60 cm", inventoryType: "BATCH" as const, stockQuantity: 10, featured: true, status: "PUBLISHED" as const, description: "Limited edition fine art print of the Virunga mountains shrouded in morning mist." },
    { name: "Tea Pickers at Dawn", slug: "tea-pickers-at-dawn", artistName: "David Mugabo", price: "650.00", categoryId: photography.id, medium: "Fine art print", dimensions: "60 Ã— 40 cm", inventoryType: "BATCH" as const, stockQuantity: 15, featured: false, status: "PUBLISHED" as const, description: "Documentary photograph of women tea pickers in the Western Province." },
    { name: "Children of Kigali", slug: "children-of-kigali", artistName: "Josephine Kaneza", price: "720.00", categoryId: photography.id, medium: "Fine art print, cotton rag", dimensions: "70 Ã— 50 cm", inventoryType: "BATCH" as const, stockQuantity: 8, featured: false, status: "PUBLISHED" as const, description: "Intimate portrait series of children growing up in modern Kigali." },
  ]
  for (const p of productData) {
    await db.product.upsert({ where: { slug: p.slug }, update: {}, create: p })
  }

  // â”€â”€ Experiences â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.experience.upsert({ where: { slug: "gorilla-trek-volcanoes" }, update: {}, create: { title: "Gorilla Trek â€” Volcanoes NP", slug: "gorilla-trek-volcanoes", shortDescription: "Track mountain gorillas in their natural habitat.", description: "Spend a transformative morning with one of the last remaining mountain gorilla families. Your expert guide will lead you through dense bamboo forest to the gorillas.", location: "Volcanoes National Park, Northern Province", durationHours: 6, pricePerPerson: 1500, groupPrice: 1200, minGroupSize: 2, maxGroupSize: 8, languages: ["English", "French", "Kinyarwanda"], meetingPoint: "Kinigi Park Headquarters", included: ["Park permit", "Expert guide", "Porters", "Lunch", "Transport from Kigali"], excluded: ["International flights", "Visa fees", "Travel insurance", "Tips"], whatToBring: ["Sturdy hiking boots", "Rain jacket", "Long trousers", "Gloves", "Water (2L)"], experienceType: "CONSERVATION", featured: true, status: "PUBLISHED" } })
  await db.experience.upsert({ where: { slug: "kigali-cultural-walking-tour" }, update: {}, create: { title: "Kigali Cultural Walking Tour", slug: "kigali-cultural-walking-tour", shortDescription: "Discover the soul of Rwanda's capital on foot.", description: "Walk through Kigali's vibrant neighbourhoods, visiting local markets, artisan workshops, and memorial sites. Learn about Rwanda's remarkable transformation.", location: "Kigali, Rwanda", durationHours: 4, pricePerPerson: 85, groupPrice: 70, minGroupSize: 1, maxGroupSize: 12, languages: ["English", "French"], meetingPoint: "Kigali Convention Centre, main entrance", included: ["Expert guide", "Market visit", "Traditional lunch", "Workshop visit"], excluded: ["Personal purchases", "Tips"], whatToBring: ["Comfortable walking shoes", "Camera", "Sun protection"], experienceType: "CULTURAL", featured: true, status: "PUBLISHED" } })
  await db.experience.upsert({ where: { slug: "village-craft-immersion" }, update: {}, create: { title: "Village Craft Immersion", slug: "village-craft-immersion", shortDescription: "Learn traditional crafts directly from village artisans.", description: "Spend a full day in a rural village learning basket weaving, pottery, and imigongo art directly from master artisans. Share lunch with a local family.", location: "Nyamata, Eastern Province", durationHours: 8, pricePerPerson: 120, groupPrice: 95, minGroupSize: 2, maxGroupSize: 10, languages: ["English", "Kinyarwanda"], meetingPoint: "Nyamata Bus Station", included: ["Craft materials", "Expert artisan teachers", "Family lunch", "Certificate of participation"], excluded: ["Transport to Nyamata", "Tips"], whatToBring: ["Old clothes (crafts can be messy)", "Camera", "Curiosity"], experienceType: "VILLAGE", featured: true, status: "PUBLISHED" } })

  // â”€â”€ Conservation Campaigns â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.conservationCampaign.upsert({ where: { slug: "virunga-reforestation-2025" }, update: {}, create: { name: "Virunga Reforestation 2025", slug: "virunga-reforestation-2025", description: "Help us plant 10,000 indigenous trees across the Virunga buffer zone, creating vital wildlife corridors for mountain gorillas.", impactStatement: "Every $10 plants one tree and supports one local farmer for a day.", goalAmount: 50000, raisedAmount: 23400, donorCount: 312, status: "ACTIVE", featured: true } })
  await db.conservationCampaign.upsert({ where: { slug: "community-education-fund" }, update: {}, create: { name: "Community Education Fund", slug: "community-education-fund", description: "Support environmental education for 500 children in communities surrounding the national parks, empowering the next generation of conservation leaders.", impactStatement: "Your donation directly funds school materials and teacher training.", goalAmount: 30000, raisedAmount: 8750, donorCount: 147, status: "ACTIVE", featured: false } })

  // â”€â”€ Blog Posts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.blogPost.upsert({ where: { slug: "inside-the-gorilla-habituations" }, update: {}, create: { title: "Inside the Gorilla Habituations", slug: "inside-the-gorilla-habituations", excerpt: "We joined rangers for a remarkable day documenting the newest gorilla family in Volcanoes National Park.", content: "<h2>A Morning with Ntambara Family</h2><p>At 5am, the mist still clung to the volcanic slopes as we gathered at Kinigi headquarters. Our ranger guide, Emmanuel, had been tracking the Ntambara gorilla family for seven years...</p><p>Mountain gorillas share 98% of their DNA with humans, and spending time with them is a humbling reminder of our place in the natural world.</p>", category: "CONSERVATION", tags: ["gorillas", "conservation", "volcanoes"], featuredImageUrl: null, featured: true, published: true, publishedAt: new Date("2025-03-15") } })
  await db.blogPost.upsert({ where: { slug: "the-art-of-imigongo" }, update: {}, create: { title: "The Ancient Art of Imigongo", slug: "the-art-of-imigongo", excerpt: "Discover the 500-year-old Rwandan geometric art form made from cow dung and natural pigments.", content: "<h2>A Living Tradition</h2><p>Imigongo is one of Rwanda's most distinctive art forms, dating back to the Kingdom of Gisaka in the 15th century. Created from a mixture of cow dung and ash, then painted with natural earth pigments, these geometric patterns tell stories of community, nature, and identity...</p>", category: "CULTURE", tags: ["art", "tradition", "imigongo"], featuredImageUrl: null, featured: false, published: true, publishedAt: new Date("2025-04-02") } })
  await db.blogPost.upsert({ where: { slug: "kigali-rising-art-scene" }, update: {}, create: { title: "Kigali's Rising Contemporary Art Scene", slug: "kigali-rising-art-scene", excerpt: "How Rwanda's capital is becoming East Africa's most exciting hub for contemporary art and culture.", content: "<h2>A New Creative Capital</h2><p>Walk through Kigali's Nyamirambo neighbourhood on a Saturday morning and you'll find something remarkable: galleries packed with young artists, their work commanding attention from collectors as far away as London and New York...</p>", category: "STORY", tags: ["kigali", "contemporary art", "culture"], featuredImageUrl: null, featured: false, published: true, publishedAt: new Date("2025-04-18") } })
  await db.blogPost.upsert({ where: { slug: "meet-the-artisans-vestine" }, update: {}, create: { title: "Meet the Artisans: Vestine's Baskets", slug: "meet-the-artisans-vestine", excerpt: "For 30 years, Vestine Nyiraneza has woven peace baskets that have found homes in galleries worldwide.", content: "<h2>Weaving Stories</h2><p>Vestine Nyiraneza's hands move with the confidence of someone who has woven the same patterns for thirty years, yet each basket she creates is entirely unique. 'Every basket carries a story,' she tells us through our interpreter...</p>", category: "STORY", tags: ["artisans", "baskets", "women"], featuredImageUrl: null, featured: false, published: true, publishedAt: new Date("2025-05-01") } })

  // â”€â”€ Reviews â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.review.createMany({ data: [
    { reviewerName: "Sophie Laurent", reviewerCountry: "France", rating: 5, comment: "The gorilla trek was a once-in-a-lifetime experience. Emmanuel was an exceptional guide who made us feel completely safe while getting us incredibly close to the gorillas. Volcano Arts Center made every detail seamless.", approved: true, featured: true },
    { reviewerName: "James Okafor", reviewerCountry: "United Kingdom", rating: 5, comment: "I purchased the Volcanic Sunrise painting and it arrived perfectly packed. The quality is extraordinary â€” it completely transforms my living room. The certificate of authenticity and the personal note from the artist were wonderful touches.", approved: true, featured: true },
    { reviewerName: "Yuki Tanaka", reviewerCountry: "Japan", rating: 5, comment: "The village craft immersion was humbling and joyful. Learning basket weaving from Vestine was a highlight of our entire Africa trip. Volcano Arts Center connects you with Rwanda's true soul.", approved: true, featured: true },
  ], skipDuplicates: true })

  // â”€â”€ Talent Profiles â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const talentUser = await db.user.findUnique({ where: { email: "talent@volcanoarts.rw" } })
  if (talentUser) {
    await db.talentProfile.upsert({ where: { userId: talentUser.id }, update: {}, create: { userId: talentUser.id, displayName: "Amina Uwase", bio: "Traditional dancer and cultural performer from the Northern Province. Member of the national Intore dance troupe for 8 years.", talentArea: "TRADITIONAL_DANCE", category: "PROFESSIONAL_ARTIST", published: true, featured: true } })
  }

  // â”€â”€ Platform Settings â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const settings = [
    { category: "payments", key: "mtn_momo_number", value: "+250 788 000 000" },
    { category: "payments", key: "bank_name", value: "Bank of Kigali" },
    { category: "payments", key: "bank_account_name", value: "Volcano Arts Center Ltd" },
    { category: "payments", key: "bank_account_number", value: "00012-3456789-01" },
    { category: "payments", key: "bank_swift", value: "BKIGRWRW" },
    { category: "payments", key: "whatsapp_number", value: "+250 788 000 001" },
    { category: "site", key: "currency", value: "USD" },
  ]
  for (const s of settings) {
    await db.platformSetting.upsert({ where: { category_key: { category: s.category, key: s.key } }, update: { value: s.value }, create: s })
  }

  console.log("Seed complete")
}

main().catch(console.error).finally(() => db.$disconnect())